"""ModelsV1.7 change owner

Revision ID: 1f2e7934b55f
Revises: c5614c268a70
Create Date: 2023-11-13 16:42:23.413133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2e7934b55f'
down_revision: Union[str, None] = 'c5614c268a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
